site_name: How to Create a UML Class Diagram with draw.io
site_url: https://kai-st.github.io/comm2216-docs-project/

nav:
  - Introduction: "index.md"
  - Create and Share a Draw.io File: "create.md"
  - Add Classes: "blocks.md"
  - Add Connectors: "connectors.md"
  - Export Your Diagram: "export.md"
  - Troubleshooting: "troubleshooting.md"
  - Glossary: "glossary.md"

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: light blue

  features:
    - navigation.footer
    - navigation.sections

  logo: assets/drawio-logo.png
  favicon: assets/drawio-logo.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kai-st/comm2216-docs-project

copyright: Copyright &copy; 2025 Pearly Li & Kai Steingarten
